[package]
name = "atelier-generators"
version = "0.0.1"
publish = false
edition = "2021"

[dependencies]

# Atelier sub-modules 
atelier-data = { workspace = true }

# Error
thiserror = { workspace = true }

# Probabilistic features
rand = { workspace = true }
rand_distr = { workspace = true }

